version: '3'

services:

  authentication-service:
    build:
      context: authentication-service
      dockerfile: authentication-service.dockerfile
    restart: always
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1

  user-service:
    build:
      context: user-service
      dockerfile: user-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    environment:
      DSN: "host=postgres port=5432 user=postgres password=postgres dbname=users sslmode=disable timezone=UTC connect_timeout=5"
    deploy:
      mode: replicated
      replicas: 1

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - "./db-data/redis:/data"
    command: redis-server --requirepass password

  postgres:
    image: 'postgres:14.2'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - "./sql-scripts/user-service.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./db-data/postgres/:/var/lib/postgresql/data/"